version: '3'
services:
  mysqldb:
    image: mysql:latest
    ports:
      - '3307:3306'
    environment:
      MYSQL_USER: user01
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: user_db
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data: